cas-postgres:
  patroni:
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 15m
        memory: 600Mi
    walE:
      enable: true
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}, has to be < 28 characters
      gcsBucket: wksv3k-prod-mb-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-wksv3k-prod-mb-backups-service-account-key # pragma: allowlist secret
    # options below are required if walE.enable is true
  namespace: wksv3k-prod
  gcs:
    bucketSuffix: mb-backups

route:
  enable: true
  host: cas-metabase-preview.pathfinder.gov.bc.ca
