{{- if .Values.networkPolicies.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-metabase.fullname" . }}-internal-by-release
  labels: {{ include "cas-metabase.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      release: {{ include "cas-metabase.name" . }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              release: {{ include "cas-metabase.name" . }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "cas-metabase.name" . }}
{{- end }}
