{{- if .Values.nginx.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "metabase.fullname" . }}-acme-home
  labels: {{ include "metabase.labels" . | nindent 4 }}

spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: {{ .Values.nginx.storageClassName }}
{{- end }}