apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metabase.fullname" . }}-nginx-config
  labels: {{ include "metabase.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen {{ .Values.nginx.port }};
      listen [::]:{{ .Values.nginx.port }};
      server_name  _;
      location / {
        proxy_pass http://localhost:{{ .Values.service.internalPort }};
      }
    }
